### ISSUE TITLE
Chat delay

### ISSUE THREAD

**Issue by paul-lrr** [Glodenox/twitch-chat-monitor#39]
This was just a random idea, but when we have the chat up on a monitor in the room where we are playing a guessing or quiz game, we usually have to turn it off to prevent chat spoiling the answers. One solution is to put a small delay in the stream to make sure that any answers that chat gives are too late to help, but unfortunately the stream has to be taken offline to add or change a stream delay, which is a bit of a pain. I was thinking that, instead of delaying the whole stream, if the just chat being displayed on the monitor could be delayed, it would be possible to dynamically change the delay in case it is too short or have the chat read normally when we aren't playing.

I guess this would involve buffering the chat messages for a set amount of time, which might be a bit tricky. TBH, it doesn't come up that often, I just thought it might be a neat feature.

**Comment by Glodenox** [comment]
The chat monitor can already add an artificial delay since July, when I implemented issue #23 😀 It can be configured without needing a reload of the chat, but there's currently no quick and easy way to enable or disable it, other than going into the settings.

I'll add a toggle for that configuration, similar to how smooth scrolling and rate limiting work. After that, it should be trivial to add another hotkey to toggle it. To improve that configuration flow further, I'm hoping to find time to look into #36, which would allow the sending of commands to the monitor via web sockets.

**Comment by Glodenox** [comment]
I forgot to include the image I had prepared to show the location in the settings: 

![chat-delay](https://user-images.githubusercontent.com/7704174/206397704-84345193-44a1-41db-9fa1-ccf77b2310ce.png)

**Comment by paul-lrr** [comment]
Wow! you are way ahead of me.  I guess I should have checked the settings page first.😄

**Comment by Glodenox** [comment]
I've now also added a checkbox in the settings and a hotkey (Ctrl+Shift+D) to quickly toggle the artificial chat delay.
