### ISSUE TITLE
Clickable links stop being clickable when "support sending messages" is on & new messages appear at bottom

### ISSUE THREAD

**Issue by evilspoons** [Glodenox/twitch-chat-monitor#49]
Hi, love the project overall, but I have found a bug. If you enable **Suport sending messages** while **New messages appear at the top** is disabled, clickable links are no longer clickable. Toggling either setting fixes the problem, so I am naively guessing a transparent part of the chat input box UI, when moved to the top, is covering the bottom of the page.

I'd be perfectly happy if the fix was just keeping the "enter message" box at the bottom when new messages appear at the bottom.

I have tested this in Firefox 119.0.1, Tor Browser 13.0.1 (built on Firefox 115.4.0esr) and Edge 119.0.2151.58 on a Windows 11 machine, as well as Firefox 119.0.1 on a Linux Mint machine. I took the first steps of disabling adblockers and stuff for the site, which didn't change anything. Edge and Tor didn't have any extensions installed in the first place.

Thanks!

**Comment by Glodenox** [comment]
The issue here seems to be related to the container for notifications like "connection lost" or "chat overload". It would seem there is one CSS rule missing there, which causes it to cover the whole chat. That's the reason why links can't be clicked.

The addition of this CSS rule will fix that, I'll try to add it later today:
```
body.show-message-entry.reverse-order .notifications {
  top: calc(14px + var(--font-size));
  bottom: auto;
}
```

**Comment by evilspoons** [comment]
Working great now. Thanks a lot!
